version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8081:8080"  # Changed from 8080 to 8081
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./.jenkins:/var/jenkins_home/workspace/hello-world
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    container_name: jenkins