name: React Native UI Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MAESTRO_CLOUD_API_KEY: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
  APP_NAME: "FrontRunner"
  SIMULATOR_NAME: "iPhone 14"
  SIMULATOR_RUNTIME: "iOS-16-2"

jobs:
  ui-test:
    name: Run Maestro UI Tests
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies with NPM
        run: npm ci
        
      - name: Setup Ruby for Cocoapods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install Cocoapods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace ${{env.APP_NAME}}.xcworkspace \
            -scheme ${{env.APP_NAME}} \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build \
            -destination "platform=iOS Simulator,name=${{env.SIMULATOR_NAME}}" \
            clean build

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "${{env.SIMULATOR_NAME}}" || true
          xcrun simctl list devices
          open -a Simulator.app

      - name: Start Metro Bundler
        run: |
          npx react-native start --port 8081 & 
          sleep 30

      - name: Create Artifact Directories
        run: |
          mkdir -p .maestro/screenshots
          mkdir -p .maestro/videos

      - name: Run Maestro Tests
        run: |
          # Verify Maestro installation
          maestro --version
          
          # Run tests with artifacts output to .maestro directory
          maestro test --output-dir=.maestro .maestro/flow.yaml || {
            echo "Maestro tests failed"
            exit 1
          }
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: maestro-test-results-${{ github.sha }}
          path: |
            .maestro/screenshots/**/*
            .maestro/videos/**/*
          retention-days: 14
          if-no-files-found: warn  # Added to make the error more informative